SELECT         VendorID::BIGINT as VendorID ,
               lpep_pickup_datetime::TIMESTAMP as lpep_pickup_datetime ,
               lpep_dropoff_datetime::TIMESTAMP as lpep_dropoff_datetime ,
               store_and_fwd_flag::VARCHAR as store_and_fwd_flag ,
               RatecodeID::BIGINT as RatecodeID ,
               PULocationID::BIGINT as PULocationID ,
               DOLocationID::BIGINT as DOLocationID ,
               passenger_count::BIGINT as passenger_count ,
               trip_distance::DOUBLE as trip_distance ,
               fare_amount::DOUBLE as fare_amount ,
               extra::DOUBLE as extra ,
               mta_tax::DOUBLE as mta_tax ,
               tip_amount::DOUBLE as tip_amount ,
               tolls_amount::DOUBLE as tolls_amount ,
               ehail_fee::DOUBLE as ehail_fee ,
               improvement_surcharge::DOUBLE as improvement_surcharge ,
               total_amount::DOUBLE as total_amount ,
               payment_type::DOUBLE as payment_type ,
               trip_type::BIGINT as trip_type ,
               congestion_surcharge::DOUBLE as congestion_surcharge ,
               cbd_congestion_fee::DOUBLE as cbd_congestion_fee 
        FROM '{0}'